resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        # Llamadas lentas
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      items:
        base-config: defecto

  # Time out
  timelimiter:
    configs:
      defecto:
        timeout-duration: 6s # Para que no ocurra timeout debe superar slow-call-duration-threshold
    instances:
      items:
        base-config: defecto

